# Generated by Django 5.0.3 on 2025-08-21 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_desc_service_operator_service_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='type_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.typesercie'),
        ),
    ]
