# Generated by Django 5.0.3 on 2025-08-23 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_created_at_service_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='Materail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('count', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'materail',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='material',
            field=models.ManyToManyField(to='services.materail'),
        ),
    ]
