# Generated by Django 5.0.3 on 2025-10-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_invoice_materail_service_invoice_invoice_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.IntegerField(choices=[(0, 'در حال پیگیری'), (1, 'اعزام تکنسین'), (2, 'انجام تعمیرات'), (3, 'پایان یافته')], default=0),
        ),
    ]
