# Generated by Django 5.0.3 on 2025-08-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('code', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('desc', models.TextField(null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
